### ISSUE TITLE
Consider moving config to XDG directory

### ISSUE THREAD

**Issue by abrouwers** [vtorri/entice#1]
In the last couple of years, there is an effort to reduce /home directory configs.  Many programs have migrated ~/.config and/or ~/.local/share/ for configs and/or data.  Arch has a nice wiki describing this:

https://wiki.archlinux.org/index.php/XDG_Base_Directory

So, it might be nice to migrate entice's config to ~/.config/entice, rather than just ~/.entirce ?

**Comment by vtorri** [comment]
telle me if f2eeee3288d10c45002d5202a2e37f327dd0809d fixes this.

**Comment by abrouwers** [comment]
Yup, it works!  I removed ~/.entice, and now I get only:

[andrew@thinkpad entice]$ find /home/andrew/ -iname "*entice*"
/home/andrew/.config/entice
