### ISSUE TITLE
entice should gracefully show an error when launching an unsupported file format

### ISSUE THREAD

**Issue by TheTechRobo** [vtorri/entice#10]
When I run entice on a PDF, it shows a blank screen. When I press the check mark button thingy, it crashes with "floating point exception". When opening, instead of putting it in this state, entice should throw an error instead of creating unexpected behaviour.

**Comment by vtorri** [comment]
please update to latest git. I did some changes. I don't see any error : 

i have created a 'pdf' directory and copy a pdf file in it. I try to display it with entice. Here, entice displays "no image found"

**Comment by TheTechRobo** [comment]
Yeah, sorry, again this issue is invalid. Very sorry about these invalid issues.
