### ISSUE TITLE
Entice seems to follow a "random" order to go through a picture sequence

### ISSUE THREAD

**Issue by triantares** [vtorri/entice#11]
When using the arrow keys to navigate a folder, entice seems to follow a logic of it's own i.e it's not the numerical order as in the file manager or even the chronological order in camera DCIM folders.

On top it only shows files numbering 0 if you navigate backwards (using arrow left) from where you started.

To test I made a small directory with the files 0-4.jpg.
opening 0.jpg jumps to 3, then 1 and refuses 4 ......showing it only when navigating backwards.

This makes it real awkward to compare adjacent pics.
I think this is a major issue. :(

**Comment by vtorri** [comment]
the logic is the one that is given by dirent API. I'm developping on Windows and on that OS, it's always ordered alphabetically. I wanted to order the list alphabetically, but i have forgotten to fix this.

You would like several kind of ordering ? like : 

- alphabetical order
- last modification date
- color-like ordering (see latest E with the background selector to have an idea)
- something else ?

**Comment by triantares** [comment]
In itself, alphabetical order is OK but failing that .... like with 1,2,3,4 or with dates like my camera, or even screenshots it definitely should look at the numerical order.
I actually think it better to do numerical first and then alphabetical ..... I mean how is this going to work in Cyrillic or Chinese?

**Comment by vtorri** [comment]
i doubt that neo-medieval cyrillic people will use entice :-) Anyway, i will propose in settings radio buttons to select alphabetical order or latest modified date. Maybe i will do that this evening.

**Comment by triantares** [comment]
> neo-medieval cyrillic people
I wouldn't call Greek or Russian that.

But when looking for a good pic from my camera, where I usually try to take a few pictures with different lighting or adjusted frame .... It's essential to them in order and in showing 0,3,2 and not 4 instead of 0,1,2,3,4 is ludicrous.
I also think it would be impossible to look through a sequence of a timeshift video frames chronologically.

Also, renaming 0,1,2,3 to a, b,c, d gives very strange ordering .... there's something very wrong there. :(

**Comment by vtorri** [comment]
@triantares please update git. I have, for now, sorted alphabetically the files
It works on Windows and manjaro

**Comment by triantares** [comment]
It works perfectly now.
Closing the issue.
