### ISSUE TITLE
Right Click Menu leaves artifact on close

### ISSUE THREAD

**Issue by TheTechRobo** [vtorri/entice#12]
When I right click ont he image for the settings, all goes well. But when I click the blank button in the top right of the screen, then press "settings", when I close it leaves a black artifact on the image.

**Comment by vtorri** [comment]
i had that bug, but i fixed it. Are you sure that you have the latest git ?
Here, i do not have that bug

**Comment by TheTechRobo** [comment]
I'll try updating later today.

**Comment by vtorri** [comment]
@TheTechRobo is the bug still here after updating ?

**Comment by TheTechRobo** [comment]
Sorry, yes this issue is invalid.
