### ISSUE TITLE
On Elive 3.8.19 Beta (E16) the buttons in the widget are black.

### ISSUE THREAD

**Issue by triantares** [vtorri/entice#14]
A picture that says it all:.
![Elive_Screenshot_2021-04-19_15:19:39__1290x711](https://user-images.githubusercontent.com/53149809/115243549-53fdc780-a123-11eb-8754-e2dea85e36da.jpg)

See the black squares left and right of the %.
Mouse over doesn't do anything either but clicking is functional.

**Comment by vtorri** [comment]
you *must* have the latest efl git. I use the flat theme, with specific features added these days. I'm not sure about icons, though.

**Comment by vtorri** [comment]
![entice](https://user-images.githubusercontent.com/1422401/115262214-9d0a4780-a134-11eb-8f33-64518dbe1ee5.png)

**Comment by vtorri** [comment]
lastest feature : frame with close button : 

![entice2](https://user-images.githubusercontent.com/1422401/115262429-d5aa2100-a134-11eb-956d-70b7f4a158fe.png)

**Comment by triantares** [comment]
Nono, this is not E24 but E16 ..... I think there's a transparency issue there.

**Comment by vtorri** [comment]
@triantares can you change a bit the code ?

entice_controls.c, remove the line 51 : 

elm_object_style_set(o, "overlay");

This one is adding transparency over the buttons

**Comment by vtorri** [comment]
tell me if it fixes your problem

**Comment by triantares** [comment]
> @triantares can you change a bit the code ?

I would if I could but I'm in fact using the installed version i.e I've installed through the Elive repositories which upgrades every time you make changes to the git entry.

Currently:
entice/buster,now 3.8.19+git60c4e1da4-6buster1 amd64 [installed]

So I've no way of editing said code other than with git...... but that'll mess with my installed version.
Given time (of which I'm short ATM) I could try that on a VirtualBox instance but don't hold your breath.

Elive Beta comes with E16 as default DE so be aware that this might make some issues unclear as to the cause when it comes to Elive users.

**Comment by vtorri** [comment]
i've just removed overlay as a test. Please test. If there is no change, i'll re-enable overlay

**Comment by Thanatermesis** [comment]
> you must have the latest efl git. I use the flat theme, with specific features added these days. I'm not sure about icons, though.

yeah, @triantares , the FLAT theme (which is for, elementary & enlightenment, both) comes from the EFL package, which apparently needed an update these days, if im not wrong it has been updated, but just in case let me update it again (if still not working try again upgrading in like 2 hours)

How much is related E16 is... it should not be related, but just make sure that you have the "composite" feature running which is more like a compatible standard today's for interfaces

**Comment by Thanatermesis** [comment]
UPDATE: for me in e16 (with the actual EFL packages available on repos) seems to work fine :thinking:  check that composite enabled in E16 preferences @triantares 

btw @vtorri the X (close) button in the Settings menu (and EXIF menu) seems to not close them

**Comment by triantares** [comment]
Hmmmm, my meson apparently is outdated: ```meson.build:1:0: ERROR:  Meson version is 0.49.2 but project requires >=0.50.```
I really hate those errors. :(

Looks like I'll have to wait a few hours until @Thanatermesis builds a new version for Elive.



> UPDATE: for me in e16 (with the actual EFL packages available on repos) seems to work fine thinking check that composite enabled in E16 preferences

Everything is up to date and composite has always been enabled.....looks like it's my set-up. Creating a new user shows buttons now but my own account doesn't. Extremely puzzling cannot find the reason yet.

Anyway looks like the issue for Entice has been seen to now. :+1:  Might as well close it.

**Comment by triantares** [comment]
As an addendum, I do get errors on closing entice as that user (other users exit cleanly) so any advice there?
---
mouse in
mouse out
mouse in
mouse out
ERR<13033>:efreet_cache ../src/lib/efreet/efreet_cache.c:432 efreet_cache_shutdown() This application has not properly closed all its desktop references!
## Copy & Paste the below (until EOF) into a terminal, then hit Enter

eina_btlog << EOF
/lib/x86_64-linux-gnu/libeina.so.1       0x7f4b500b1aec 0x7f4b50087000
/lib/x86_64-linux-gnu/libeina.so.1       0x7f4b500b2c31 0x7f4b50087000
/lib/x86_64-linux-gnu/libeina.so.1       0x7f4b500b4253 0x7f4b50087000
/lib/x86_64-linux-gnu/libefreet.so.1     0x7f4b5017a166 0x7f4b5015d000
/lib/x86_64-linux-gnu/libefreet.so.1     0x7f4b50165433 0x7f4b5015d000
/lib/x86_64-linux-gnu/libeio.so.1        0x7f4b4fcb0875 0x7f4b4fc9d000
/lib/x86_64-linux-gnu/libelementary.so.1         0x7f4b5073ff6d 0x7f4b50503000
/lib/x86_64-linux-gnu/libelementary.so.1         0x7f4b50740567 0x7f4b50503000
/usr/bin/entice  0x564e4346fb26 0x564e4346a000
/lib/x86_64-linux-gnu/libc.so.6  0x7f4b50a0809b 0x7f4b509e4000
/usr/bin/entice  0x564e4346fb7a 0x564e4346a000
EOF

----

**Comment by vtorri** [comment]
i need debug symbols, otherwise i can't do much, unfortunately

on the other hand, i would like to remove efreet usage...

**Comment by triantares** [comment]
> i need debug symbols, otherwise i can't do much, unfortunately


How would I acquire those, in the case of entice?

Though there clearly is something wrong with my user settings. :(
So I think the issue itself can be closed.

**Comment by vtorri** [comment]
usually, when you compile, pass at least -g to CFLAGS

export CFLAGS="-g -Og"

**Comment by vtorri** [comment]
@triantares i can decrease meson version if you want

**Comment by triantares** [comment]
> i can decrease meson version if you want

That would be cool (not only for me) as the version 49 that I've got is the current version on Debian Buster.

**Comment by vtorri** [comment]
@triantares i've downgraded meson version

@Thanatermesis the X of settings and exif do close the panels

**Comment by vtorri** [comment]
@triantares if you update to latest git, do you still have a segfault ?

if yes compile with debug symbols and : 

gdb --args entice file1 file2...

or whatever you pass to entice

then, in gdb prompt : 

run

and paste the output

**Comment by triantares** [comment]
Oopsie!
Sorry forgot to answer.

I didn't compile the latest with debug enabled so I don't have any output there.
It turns out that if I create a new user and use entice from there, the buttons show up fine.

Apparently it's a setting in my e16 config ..... I have no idea what is causing it, though.

**Comment by vtorri** [comment]
you can ask Kim Wolder (the current maintainer of e16)

**Comment by Thanatermesis** [comment]
what about an issue in your elementary_config (selected theme?) than in e16 ? :thinking: , entice uses elementary theme and i don't think e16 has much relation with it

**Comment by vtorri** [comment]
e16 uses imlib2 as graphic engine, so indeed no relation at all.
