### ISSUE TITLE
More mimetypes

### ISSUE THREAD

**Issue by Thanatermesis** [vtorri/entice#3]
Since it supports many image formats, I suggest to include them in the mimetypes list of the .desktop file (if im not wrong, this will make the filemanagers or other applications being able to show Entice as an option or tool to open the files with)

Actually it only includes:

> MimeType=image/jpeg;image/png;image/gif

Example:
> ~ ❯❯❯ file --mime-type /tmp/foo.webp
> /tmp/foo.webp: image/webp

**Comment by vtorri** [comment]
Indeed, that is something i wanted to do and i forget it... thanks for the reminder

**Comment by vtorri** [comment]
tell me if it's better, now. If it's ok, please close the issue
