### ISSUE TITLE
Feature request: EXIF and properties data showing up

### ISSUE THREAD

**Issue by Thanatermesis** [vtorri/entice#5]
Could be nice if when we mouse-in the interface, we can see in the left side as a panel with basic EXIF data from the viewing image, just like other properties like resolution / size / format :)

**Comment by vtorri** [comment]
size is already in the title bar :)
maybe i'll add that.

**Comment by vtorri** [comment]
first attempt : https://ibb.co/bgD8RFj

**Comment by TheTechRobo** [comment]
that looks pretty good! @thanatermesis can you confirm?

**Comment by vtorri** [comment]
the code is now in git

**Comment by vtorri** [comment]
closing, open another issue if you want more (or less) exif data to be shown
