### ISSUE TITLE
More of a request.....simple highlights

### ISSUE THREAD

**Issue by triantares** [vtorri/entice#6]
I'd love to have options to i.e highlight or place an arrow in part of an image ..... like in the screenshot app on E24.

Quite often I find myself needing to open another app like "gimp", "xournal" or "krita" simply to accentuate part of an image in my workflow.....it would be awesome to be able to use the viewer to select an image (or in time maybe just a part of it) and add what I need there, like a circle or an arrow.

All very rudimentary (a line, an arrow, a box or circle) of course ...... the named other apps can do it quite well for heavy duty, if need be.

**Comment by vtorri** [comment]
you want to overlay a box, etc... over the image ?

please provide a screenshot of what you want :) So that I understand correctly what you want

**Comment by TheTechRobo** [comment]
@vtorri i think triantares means that he could add shapes, text, boxes, etc... to the image ... basic editing functions

**Comment by vtorri** [comment]
in that case, no. My plan is to do an image viewer, that's all. No basic editing. The app you request would be another app.

**Comment by Thanatermesis** [comment]
I found this useful too for doing something, like for example you want to send an image to someone via email / whatsapp-web but you want to "hilight" something (like "hey! check this element HERE")

Also as another suggestion (not sure if is not the same), being able to hilight a portion of the image (like, selecting a box) and by hitting "ctrl +c", we have this piece of the image copied to the clipboard, ready to be send or used in other applications :thinking:

**Comment by triantares** [comment]
> to "hilight" something (like "hey! check this element HERE")

It would be a nice feature but does indeed sound more like an "edit" feature than the simple Ctrl-c to copy the file path.

I'll leave it up to @vtorri to decide if he wants to do that or not.
If not I'll gladly close the issue.

**Comment by vtorri** [comment]
selection box, why not; I'll think about that
