### ISSUE TITLE
Right click menu doesn't close

### ISSUE THREAD

**Issue by triantares** [vtorri/entice#7]
When right clicking, an options window opens but cannot be closed through the top bar.
Another right click closes it but this isn't "normal" behavior one would expect....IMO: add a close option :)

**Comment by vtorri** [comment]
when the options window is opened, to cloe it, you can either : 

- right click
- press Esc key
- click on the option icon at the top

isn't it sufficient ?

**Comment by TheTechRobo** [comment]
> isn't it sufficient ?

not for people who aren't used to it. people might get confused.

**Comment by vtorri** [comment]
i'll think about it

Note that README.md is describing (or will describe...) what can be done

**Comment by vtorri** [comment]
btw, do you prefer a"close" button at the bottom (left or right) or a icon (a 'X' icon for example) to close the setting window ?

**Comment by triantares** [comment]
> btw, do you prefer a"close" button at the bottom (left or right) or a icon (a 'X' icon for example) to close the setting window ?

I think simply adhering to the standard used by the DE will do. 
In this (E) case I'd go for a top right, in the top bar.

**Comment by vtorri** [comment]
note that it's not really a window. I'll add an 'X' at the top right, then

**Comment by triantares** [comment]
> note that it's not really a window. I'll add an 'X' at the top right, then

Consider this issue closed IMO.

**Comment by vtorri** [comment]
something like that : https://ibb.co/Wykhpyj ?

**Comment by vtorri** [comment]
now it's in git, closing
